import type { CctvCamera } from "./types";

export const CCTV_CAMERAS: CctvCamera[] = [
  {
    id: "cam-1",
    name: "냉장 구역 1",
    location: "냉장 보관함 앞",
    description: "냉장 구역 전경",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam1",
  },
  {
    id: "cam-2",
    name: "상온 구역",
    location: "상온 보관함 앞",
    description: "상온 구역 전경",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam2",
  },
  {
    id: "cam-3",
    name: "미정",
    location: "미정",
    description: "미정 확인용",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam3",
  },
    {
    id: "cam-4",
    name: "미정",
    location: "미정",
    description: "미정 확인용",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam4",
  },
    {
    id: "cam-5",
    name: "미정",
    location: "미정",
    description: "미정 확인용",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam5",
  },
    {
    id: "cam-6",
    name: "미정",
    location: "미정",
    description: "미정 확인용",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam6",
  },
    {
    id: "cam-7",
    name: "미정",
    location: "미정",
    description: "미정 확인용",
    enabled: true,
    streamType: "iframe",
    streamUrl: "http://14.82.64.55:31984/stream.html?src=cam7",
  },
];